In [3]:
animaux = {
    "chien": "dog",
    "Souris": "mouse",
    "Chat": "cat",
    "Oiseau": "bird"
}
print(animaux)

fruits = {
    "bananes": ["banana"],
    "tomate": ["tomate"],
    "pommes": ["maçã"],
    "Orange": ["Laranja"]
}
print(fruits)

{'chien': 'dog', 'Souris': 'mouse', 'Chat': 'cat', 'Oiseau': 'bird'}
{'bananes': ['banana'], 'tomate': ['tomate'], 'pommes': ['maçã'], 'Orange': ['Laranja']}

In [4]:
dictionaire = {
    "dict1": animaux,
    "dic2": fruits
}
dictionaire

{'dict1': {'chien': 'dog', 'Souris': 'mouse', 'Chat': 'cat', 'Oiseau': 'bird'},
 'dic2': {'bananes': ['banana'],
  'tomate': ['tomate'],
  'pommes': ['maçã'],
  'Orange': ['Laranja']}}

In [8]:
fruits.values()

dict_values(['banana', 'tomate', 'maçã', 'Laranja'])

In [10]:
fruits.keys()

dict_keys(['bananes', 'tomate', 'pommes', 'Orange'])

In [15]:
fruits["bananes"] = "banana"

In [21]:
len(fruits.keys())

3

In [37]:
fruits

{'bananes': ['banana'],
 'tomate': ['tomate'],
 'pommes': ['maçã'],
 'Orange': ['Laranja']}

In [38]:
pd.DataFrame(fruits)

  bananes  tomate pommes   Orange
0  banana  tomate   maçã  Laranja

In [98]:
import pandas as pd
list_task = {
    "Name": ['Jeovani Paxe', "Bruno de Carvalho", "Sandro Direito"],
    "Tasks":['Conversar com a Babiele as 12h', "Fazer a nova musica com o Scro Q Cuia", "Terminar o curso de Ciência da Computação"]
}
# list_task
data = pd.DataFrame(list_task)
data[["Name", "Tasks"] ]

                Name                                      Tasks
0       Jeovani Paxe             Conversar com a Babiele as 12h
1  Bruno de Carvalho      Fazer a nova musica com o Scro Q Cuia
2     Sandro Direito  Terminar o curso de Ciência da Computação

In [85]:
list_task["Name"][1]
data[["Name"]][data["Name"] == data["Name"][1]]


# ou
# data2 = data[data["Name"] == data["Name"][1]]]
# data2[["Name"]]

                Name
1  Bruno de Carvalho

In [100]:
data2 = data[data["Name"] == data["Name"][1]]
data2[["Name"]]

                Name
1  Bruno de Carvalho

In [91]:
data_array = np.array(data)
data_array

array([['Jeovani Paxe', 'Conversar com a Babiele as 12h'],
       ['Bruno de Carvalho', 'Fazer a nova musica com o Scro Q Cuia'],
       ['Sandro Direito', 'Terminar o curso de Ciência da Computação']],
      dtype=object)

In [94]:
data_array[1][1]

'Fazer a nova musica com o Scro Q Cuia'

In [107]:
# Apagar um certa linha da minha tabela.
data2 = data[data["Name"] == data["Name"][1]]
data2

                Name                                  Tasks
1  Bruno de Carvalho  Fazer a nova musica com o Scro Q Cuia

In [112]:
del list_task['Name'][1]
del list_task['Tas'][1]

{'Name': ['Jeovani Paxe', 'Bruno de Carvalho', 'Sandro Direito'],
 'Tasks': ['Conversar com a Babiele as 12h',
  'Fazer a nova musica com o Scro Q Cuia',
  'Terminar o curso de Ciência da Computação']}

In [3]:
import numpy as np

a = np.array(
    [
        [10, 11, 23],
        [23, 12, 45],
        [44, 34, 13]
    ]
)
a

array([[10, 11, 23],
       [23, 12, 45],
       [44, 34, 13]])

In [12]:
lista = [12, 3,4,1234]
lista2 = [2,4,34]
new_array = np.array((lista, lista2))
print(new_array.dtype.name)
# print(type(new_array))

object
<class 'numpy.ndarray'>

c:\Users\jeova\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  This is separate from the ipykernel package so we can avoid doing imports until

In [2]:
import numpy as np
parametres = {
    "w1": np.random.randn(10,1)
}

print(parametres)
print("Le valeur maximom c'est: ",max(parametres["w1"]))

{'w1': array([[-1.4503457 ],
       [ 1.45595965],
       [ 1.08874546],
       [ 0.28139093],
       [-0.20951003],
       [-0.38983935],
       [ 0.51937081],
       [-0.4355889 ],
       [ 0.3654874 ],
       [-0.42505188]])}
Le valeur maximom c'est:  [1.45595965]

# **Tout sur le dicitonaire**

### **Nous ferons les CRUD avec dictinaire**

In [33]:
CE = {
    "disciplinas":[
        "Algebra",
        "Machine Learning",
        "Analise de dados"
    ],
    "Materia": [
        "Soma de matrises",
        "List comprenhetion",
        "Manipulação de dados"
    ],
    "Tempo": '20min'
}
CE

{'disciplinas': ['Algebra', 'Machine Learning', 'Analise de dados'],
 'Materia': ['Soma de matrises', 'List comprenhetion', 'Manipulação de dados'],
 'Tempo': '20min'}

### **Apagar um elemento da lista**

In [34]:
#Pagafando por nome
CE["disciplinas"].pop(CE['disciplinas'].index("Analise de dados"))
print("Done.")

Done.

In [35]:
CE["disciplinas"]

['Algebra', 'Machine Learning']

In [36]:
# usando filas para add a discplinas estatistica no lugar do Macinlearnig.
first_val = []
first_val.append(CE["disciplinas"].pop(1))
first_val

['Machine Learning']

In [37]:
CE["disciplinas"].append("Estatistica")
CE["disciplinas"].append(first_val[0])
CE["disciplinas"]

['Algebra', 'Estatistica', 'Machine Learning']

In [38]:
import pandas as pd
df = pd.DataFrame(CE)
df

        disciplinas               Materia  Tempo
0           Algebra      Soma de matrises  20min
1       Estatistica    List comprenhetion  20min
2  Machine Learning  Manipulação de dados  20min

In [8]:
v = []
type(v)

list

In [8]:
list = [
    "Carlos",
    "Vander",
    "Bruno",
    "Sandra"
]
list

['Carlos', 'Vander', 'Bruno', 'Sandra']

In [40]:
import numpy as np
list = np.random.rand(10)
list

array([0.30283018, 0.46706566, 0.09246866, 0.99895119, 0.47857886,
       0.92968555, 0.51945628, 0.52284752, 0.11442386, 0.49685499])

In [41]:
list.max()

0.9989511854548636

In [118]:
list2 = np.random.randn(10)
print("Lista: ", list2)
print("\n Maior valore da lista: ",list2.max())
print("\n Menor valore da lista: ",list2.min())

Lista:  [-0.05590218 -2.33153824 -0.56608697 -0.59663157 -0.20520856  1.52147147
  1.87560867  0.25311956  0.8146107   1.35057362]

 Maior valore da lista:  1.8756086692292706

 Menor valore da lista:  -2.3315382358049965

In [169]:
list3 = np.random.randint(2, 21, 20)
print("Lista: ", list3)
print("\n Maior valore da lista: ",list3.max())
print("\n Menor valore da lista: ",list3.min())

Lista:  [ 3  2 14 17  5  7  3  5 15  9 14 14  8  5  8  7 14  4 16 20]

 Maior valore da lista:  20

 Menor valore da lista:  2

In [170]:
dados = {
    'nome': 'Pedro',
    'idade': 30
}
print(dados)

{'nome': 'Pedro', 'idade': 30}

In [171]:
dados['Nacionalidade'] = 'Angolana'
dados

{'nome': 'Pedro', 'idade': 30, 'Nacionalidade': 'Angolana'}

In [173]:
del dados['Nacionalidade']
print('done')
print(dados)

done
{'nome': 'Pedro', 'idade': 30}

# **Criando o dicionario filmes**

In [1]:
filmes = {
    'Titulo': 'Cobra Kai',
    'Ano':2024,
    'Genero': 'Drama, ação, suspanse',
    'Legenda': 'Portugês e Inglês',
    'Descricão': 'Um valoriorfgfgfgfgfgfgfgefggeegegegetge'  
}
filmes

{'Titulo': 'Cobra Kai',
 'Ano': 2024,
 'Genero': 'Drama, ação, suspanse',
 'Legenda': 'Portugês e Inglês',
 'Descricão': 'Um valoriorfgfgfgfgfgfgfgefggeegegegetge'}

In [2]:
for filter_filmes in filmes.items():
    print(filter_filmes)

('Titulo', 'Cobra Kai')
('Ano', 2024)
('Genero', 'Drama, ação, suspanse')
('Legenda', 'Portugês e Inglês')
('Descricão', 'Um valoriorfgfgfgfgfgfgfgefggeegegegetge')

In [3]:
for k, v in filmes.items():
    print(f' {k} é {v}')

 Titulo é Cobra Kai
 Ano é 2024
 Genero é Drama, ação, suspanse
 Legenda é Portugês e Inglês
 Descricão é Um valoriorfgfgfgfgfgfgfgefggeegegegetge

In [48]:
# Printar um keys e values
k = filmes.keys()

k0 = list(k)
cherche = input('O que procura: ')
cherche = cherche.capitalize()
k = k0[k0.index(cherche)]

v0 = k0.index(cherche)
print(v0)
v = filmes.values()
v = list(v)
v = v[v0]

print(f'{k} é {v}')

3
Legenda é Portugês e Inglês

In [21]:
# experimenter le suit de fibonacci
def fibonacci(n):
    a = 0
    b = 1
    f = [a]
    while b < n:
        a,b = b, a+b
        f.append(b)
    return f
fibonacci(1009)

[0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]